PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS official (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lastname TEXT NOT NULL,
    firstname TEXT NOT NULL,
    title TEXT
);

CREATE TABLE IF NOT EXISTS school (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

ALTER TABLE records ADD COLUMN official_id INTEGER REFERENCES official(id) ON DELETE RESTRICT;
ALTER TABLE records ADD COLUMN school_id INTEGER REFERENCES school(id) ON DELETE SET NULL;
